apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ include "vault-secrets.fullname" . }}
  labels:
    {{- include "vault-secrets.labels" . | nindent 4 }}
spec:

  # Mount path of the secrets backend
  mount: {{ .Values.mount }}

  # Path to the secret
  path: {{ .Values.vaultPath }}

  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: {{ .Values.destination.name }}

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: {{ .Values.vaultAuthRef | default "vault-auth" }}
